In [5]:
import numpy as np

In [2]:
np.sqrt(25)

5.0

# Arrays

## np.aray()

In [3]:
a = [0, 1, 2, 3, 4, 5]
type (a)

list

In [4]:
type (np.array(a))

numpy.ndarray

## np.arangel()

In [5]:
b = np.arange (4 ,24, 2) #Hace un array de rango 4 a 24 de dos en dos, no añade el último número
print (b)

[ 4  6  8 10 12 14 16 18 20 22]


## np.linspace()

Genera una cantidad de números (por defento 50) entre dos números que se especifiquen de una forma lineal.

In [6]:
c = np.linspace(1,50)
print (c)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


In [7]:
cc = np.linspace(1, 50, 5)
print (cc)

[ 1.   13.25 25.5  37.75 50.  ]


## np.zeros() y np.ones()


Genera un array de la longitud que queramos llena de zeros

In [18]:
d = np.zeros(50)
d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
e = np.ones(50)
e

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Dimensiones

In [20]:
array_2d = np.array([d, e])

In [21]:
array_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]])

## array.shape

Contiene información del array creado

In [22]:
array_2d.shape

(2, 50)

## array.size()

In [23]:
array_2d.size

100

## array.ndim()

ndim nos dice el número de dimensiones de un array

In [ ]:
array_2d.ndim

## Operation with arrays 

In [ ]:
list_1 = [1, 2, 3]
list_2 = [4, 5, 6]

In [ ]:
array_1 = np.array(list_1)
array_2 = np.array(list_2)

In [ ]:
list_1 * list_2

Como se puede ver python no es capaz de multiplicar listas

In [ ]:
array_1*array_2

No obstante numpy nos permite hacerlo de forma eficiente y rápida, si quisieramos hacerlo en python habría que hacer un bucle for:

In [ ]:
[num1*num2 for num1, num2 in zip(list_1,list_2)]

# Funciones

## np.reshape()

In [21]:
array_2d.size

100

In [ ]:
array_2d.shape

In [24]:
f = np.reshape(array_2d, (1, 100))

In [16]:
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [25]:
ff = np.reshape(array_2d, (5,20))

In [20]:
ff

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

## array.T (Transpose)

In [7]:
 a = np.array(([1, 2, 3, 4, 5], [10, 20, 30, 40 ,50]))
a

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [8]:
a.shape

(2, 5)

Este array tiene 2 dimensiones y 5 lementos por dimension

In [9]:
a.T

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50]])

In [11]:
a.T.shape

(5, 2)

## Np.random

### np.random.randint

In [12]:
np.random.randint(0, 300) #Número aleatorio entre 1 y 300

19

## np.where

In [26]:
array_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]])

In [28]:
np.where(array_2d == 1, array_2d * 10 , array_2d -5) #Dónde el elemento sea = 1 multiplicar por 10, si no, resta 5

array([[-5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [32]:
np.where(array_2d == 1, array_2d * 10, array_2d) #Dónde el elemento sea = 1 multiplicar por 10, si no, dejalo igual.

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

# Estadística

## Distribuciones

In [42]:
array_normal = np.random.normal(1.75, 0.05, 1000) #Genera una distribución normal con media de 1,75, desviacion estandar de 5 cm 
                                          #(Donde entran el 68% de todos los valores) con una muestra n = 1000
print (array_normal)

[1.84375622 1.83194035 1.68094714 1.67553083 1.71859094 1.69073232
 1.79397736 1.68862517 1.79967864 1.67956564 1.75058667 1.86386034
 1.75632751 1.70668794 1.72090807 1.76817837 1.76282582 1.67809954
 1.77080013 1.73767185 1.67474865 1.78204999 1.80007431 1.7904051
 1.75708781 1.76561843 1.76621799 1.84670831 1.67519885 1.77427789
 1.69725616 1.73313444 1.77121762 1.80486664 1.69660209 1.78180465
 1.68574491 1.76192999 1.74477447 1.73708318 1.6449996  1.69481389
 1.77174721 1.82040661 1.78648525 1.71837001 1.78094127 1.65907873
 1.7694843  1.74953055 1.77467685 1.77579517 1.78141559 1.66393914
 1.73156572 1.69058295 1.73843422 1.82951583 1.71551408 1.80913467
 1.81956123 1.77041388 1.79437606 1.75128602 1.79696442 1.76313297
 1.75416896 1.73488688 1.79869267 1.73749884 1.77534237 1.79001983
 1.87127513 1.76159007 1.73376815 1.65681279 1.7474837  1.77071977
 1.74607172 1.68411183 1.76687723 1.79768341 1.75621365 1.77563634
 1.70684726 1.76687862 1.83180259 1.74206772 1.77790415 1.73610

## np.mean

In [43]:
np.mean(array_normal) #Media

1.7506885107947223

## np.median

In [44]:
np.median(array_normal) #Nos da la mediana, el valor que se encuentra en la mitad, en este caso el número 500 ya que n= = 1000

1.7514360645174547

## np.std

In [46]:
np.std (array_normal) #Desviación standar

0.048322124797311856